---
- hosts: all
  become: true
  tasks:
  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - mongodb

  - name: Allow remote connections
    lineinfile:
        dest: /etc/mongodb.conf
        regexp: 'bind_ip = 127.0.0.1'
        line: "bind_ip = 127.0.0.1,192.168.50.80"

  - name: Restart service mongodb
    systemd:
      state: restarted
      daemon_reload: yes
      name: mongodb